# configuration specific to creating s3 connections
s3:
  src_endpoint_url: "https://s3.amazonaws.com"
  src_bucket: "deutsche-boerse-xetra-pds"
  trg_endpoint_url: "https://s3.amazonaws.com"
  trg_bucket: "xetra-report"

# configuration specific to the source
source:
  src_input_date: "2020-09-17"
  src_columns:
    [
      "ISIN",
      "Mnemonic",
      "Date",
      "Time",
      "StartPrice",
      "EndPrice",
      "MinPrice",
      "MaxPrice",
      "TradedVolume",
    ]
  src_col_date: "Date"
  src_col_isin: "ISIN"
  src_col_time: "Time"
  src_col_min_price: "MinPrice"
  src_col_start_price: "StartPrice"
  src_col_max_price: "MaxPrice"
  src_col_traded_vol: "TradedVolume"

# configuration specific to the target
target:
  trg_prefix: "daily/"
  trg_key_date_format: "%Y%m%d"
  trg_format: "parquet"
  trg_col_isin: "isin"
  trg_col_date: "date"
  trg_col_op_price: "opening_price"
  trg_col_clos_price: "closing_price"
  trg_col_min_price: "min_price"
  trg_col_max_price: "max_price"
  trg_col_dail_trad_vol: "traded_volume"
  trg_col_ch_prev_clos: "pct"

# Logging configuration
logging:
  version: 1
  formatters:
    xetra:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    # console:
    #   class: logging.StreamHandler
    #   formatter: xetra
    #   level: DEBUG
    file:
      class: logging.handlers.WatchedFileHandler
      formatter: xetra
      filename: xetra-jobs.log
  root:
    level: DEBUG
    handlers: [file]
